spring:
  application:
    name: dubbo-nacos-consumer

demo:
  service:
    version: 1.0.0

nacos:
  host: 192.168.52.154
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}

server:
  port: 8082